### ISSUE TITLE
Changes not auto reload

### ISSUE THREAD

**Issue by kahwooi** [vuejs/vue-hot-reload-api#36]
Using Vuejs 1.0.26 with webpack.

I have the vue hot reload installed:

`"vue-hot-reload-api": "^2.0.6"`

Then I start the webpack dev server, and able to view the page sing http://localhsot:8080:

`webpack-dev-server --inline --hot`

 Page changes is not auto reload, I have to run webpack command to see the changes.

I saw many sample on the internet is using Vuejs 1, or this only work with Vujs 2?

**Comment by MikeBull94** [comment]
From the [`README`](https://github.com/vuejs/vue-hot-reload-api/blob/master/README.md):

> Note: vue-hot-reload-api@2.x only works with vue@2.x
