### ISSUE TITLE
hot reload clearing data

### ISSUE THREAD

**Issue by beebase** [vuejs/vue-hot-reload-api#38]
I'm trying to make quasar-framework and vuefire work together but my data gets cleared after each hot reload. Quasar-framework suggested to open an issue here. Is this something that can be fixed in your source code?

More info:
https://github.com/rstoenescu/quasar-framework/issues/87
https://github.com/vuejs/vuefire/issues/29

**Comment by laurentpayot** [comment]
@beebase I used to have the same issue, it was fixed in Quasar v0.8 (powered by Vue 2).

**Comment by posva** [comment]
Got fixed with Quasar 0.8. Turned out not to be related to this.
Can be closed

**Comment by beebase** [comment]
😄
