### ISSUE TITLE
State not preserved during HMR when <script> is changed

### ISSUE THREAD

**Issue by locobert** [vuejs/vue-hot-reload-api#39]
I have tried the browserify and the webpack templates using vue-cli. In both cases, the state is preserved during HMR when I change the template portion, but not when I change the script portion of the `*.vue` file.

To reproduce: 
- modify `src/components/Hello.vue` of the vue-cli created example:

``` html
<template>
  <div id="hello">
    <h1>{{ count }}</h1>
    <button v-on:click='inc'>inc</button>
    <button v-on:click='count -= 1'>dec</button>
  </div>
</template>

<script>
export default {
  name: 'hello',
  data () { return { count: 1 } },
  methods: { inc: function() { this.count += 1} }
}
</script>
```
- run the example with `npm run dev`
- press 'inc' a few times to change the state
- change `count -= 1` to `count -= 2` in the template part
  - after HMR, the counter value is preserved
- change `count += 1` to `count += 2` in the script part
  - after HMR, the counter value is reset to 1

Tested on: Chrome & Firefox on macOS & Windows

An example project using Vue.js 1.0 and the associated vueify+template I've created a few weeks ago preserves the state in both cases.

**Comment by yyx990803** [comment]
This is an intentional decision in 2.0: because unlike template changes (which is a pure render function underneath), JavaScript code change can be impure (e.g. lifecycle hooks). Also, the behavior can be ambiguous when you edit the initial state in `data()`. In 2.0, editing `<script>` always cause the affected instance to reload from the initial state.

**Comment by thejoecode** [comment]
This page really needs to be updated to reflect that decision. I just spent a morning trying to figure out why hot reloading was not working: https://vue-loader.vuejs.org/en/features/hot-reload.html

I re-read the page a couple times and don't see how I was supposed to understand it like I do now from reading your comment.

**Comment by yyx990803** [comment]
@thejoecode thanks, we will make sure to update that page :)
