### ISSUE TITLE
同时直接使用 vue & vuex 外链时候 报错 "$store" is not defined

### ISSUE THREAD

**Issue by lilijialiang** [vuejs/vue-hot-reload-api#40]
vue@2.0.3 / vuex@2.0.0 同时使用 script 标签引入时候，发现报错

![image](https://cloud.githubusercontent.com/assets/12247242/19958914/af43d21e-a1dd-11e6-9cce-cc721304363a.png)

而报错 vue.js 来源于 node_modules，请问外链引入的 Vue 对象为何错误发生在 node_modules 上的？

实验1 换为同时 import vue & vuex 则没有出现这样的错误
实验2 换为旧版本 vue-hot-reload-api 也没有出现这样的错误，但热加载不了
实验3 禁止 webpack 热加载，同时外链，也没有出现这样的错误

**Comment by azfly** [comment]
你是不是没有将store注入根实例

**Comment by lilijialiang** [comment]
深入了解源码后，发现自身使用问题，Close
