### ISSUE TITLE
SSR support

### ISSUE THREAD

**Issue by romandragan** [vuejs/vue-hot-reload-api#53]
When using the plugin in SSR application there is `window is not defined` issue at [`index.js:3`](https://github.com/vuejs/vue-hot-reload-api/blob/master/index.js#L3).

What about fixing it with changing this:
```js
var map = window.__VUE_HOT_MAP__ = Object.create(null)
```
to:
```js
var map = (typeof window !== 'undefined'
    ? (window.__VUE_HOT_MAP__ = Object.create(null))
    : Object.create(null))
```

Then, Server-Side Rendering would be work fine.

P.S. @yyx990803, if you prefer, I could submit PL for that.

**Comment by yyx990803** [comment]
You should not be bundling this into your server bundle (that's the default if using `vue-loader`) since hot reload doesn't work on the server.

**Comment by romandragan** [comment]
@yyx990803, OK that sounds logical. Can you please advise me, how to exclude `vue-hot-loader-api` node module from webpack server bundle?

**Comment by yyx990803** [comment]
I'm not sure what your configuration looks like, but `vue-loader` automatically excludes it from the server bundle by detecting `this.target === 'node'` in the loader context. If you are using `vue-hot-reload-api` yourself in some unconventional way, then I'm afraid I can't help you.

**Comment by romandragan** [comment]
I use `vue-hot-reload-api` without `vue-loader` because I need HMR functionality in production on nginx server, not by using node or webpack-dev-server. I just manually check if updates are available with `module.hot.check` and then do `api.reload(...)` as you've described [here](https://github.com/vuejs/vue-hot-reload-api).

To solve issue I've implemented custom module, that checks if it's browser and only then it does `require('vue-hot-reload-api')`. Otherwise it returns null.

**Comment by romandragan** [comment]
@yyx990803, by the way, do you know if rolling back hot applied changes could be implemented in some way using webpack's HMR?
