### ISSUE TITLE
Support for Vue 2.5+ with Typescript?

### ISSUE THREAD

**Issue by jiayexie** [vuejs/vue-hot-reload-api#63]
Hi, I'm trying to add hot reload capability to my Vue 2.5 project with Typescript. I'm using `Vue.extend()` to define new components and they're not `ComponentOptions` type any more, and so the Usage documentation with the `ComponentOptions` instances seems to not apply any more. Is it possible to enable hot reload for components defined with `Vue.extend()`?

**Comment by yyx990803** [comment]
Already extended constructors are supported too.
