### ISSUE TITLE
[Bug] Cannot create property 'xxx' on boolean 'true' with Vue 2.6.7

### ISSUE THREAD

**Issue by sindrepm** [vuejs/vue-hot-reload-api#73]
After update to Vue 2.6.7 I get the following error when hot reloading a component with scoped slots.
```
TypeError: Cannot create property 'items' on boolean 'true'
    at resolveScopedSlots (vue.runtime.esm.js?2b0e:2890)
```
I traced it back to https://github.com/vuejs/vue-hot-reload-api/blob/master/src/index.js#L259 which passes res=true to the `resolveScopedSlots` function:

https://github.com/vuejs/vue/blob/v2.6.7/src/core/instance/render-helpers/resolve-scoped-slots.js#L20

This works fine on Vue 2.6.6.

**Comment by LinusBorg** [comment]
Probably a sideffect of 7ec4627902020cccd7b3f4fbc63e1b0d6b9798cd

```
instance._u = slots => original(slots, true)
```
should now be:
```javascript
instance._u = slots => original(slots, null, true)
```
